export { COMPUTATION } from './types'
export { generateSpikingVector } from './generateSpikingVector'
export { getConfig } from './getConfig'
export { getConfigGPU } from './getConfigGPU'
export { getConfigCPU } from './getConfigCPU'
export { generateBitonicSortingNetworkOptimized } from "./generateBitonicSortingNetworkOptimized"
export { generateBitonicSortingNetwork } from "./generateBitonicSortingNetwork"
export { getFinalConfig } from "./getFinalConfig"
export { getFinalConfigOptimized } from "./getFinalConfigOptimized"